### ISSUE TITLE
create favicon.ico

### ISSUE THREAD

**Issue by ieahleen** [ieahleen/habitican-randomizer#47]
Maybe a pair of dice?

**Comment by ieahleen** [comment]
It's 33x32 pixel, if you can shave off one pixes so that i becomes 32x32 I think it would be good!

**Comment by onthegocode** [comment]
Okay great! If possible could you assign me the issue thank you.

**Comment by onthegocode** [comment]
@ieahleen Here's the 32x32 image let me know if you'd like to have other sizing options. 
![favicon](https://user-images.githubusercontent.com/34843760/194382780-62bf1fb2-a31a-4619-9ee9-064b28db7d75.png)

**Comment by ieahleen** [comment]
it's a favicon, as long as it works for that it's fine

**Comment by onthegocode** [comment]
Okay sounds good!

**Comment by ShivSitaram** [comment]
Since the action hasn't been done yet... I created one that I think looks good. @ieahleen can choose whichever she likes... I'm just posting this as another option:

![favicon](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAKq2lDQ1BJQ0MgUHJvZmlsZQAASImVlwdUU0kXx+e99EZLQEBK6E2QTgApIbRQpFdRCUmAUGIMBBA7sriCa0FFBCu6SlGw0uyIYmERUMC+QRYVZV0s2FDZBxzC7n7tfPecOfM7N3fuvTPvTc7/AUBR4IhEabACAOnCTHGojwc9OiaWjnsG8IAGlIEJsOVwM0TM4OAAgNj0/Hf70AugifmO+USuf/39v5oij5/BBQAKRjiBl8FNR/g0Ml5yReJMAFD7Eb9edqZoglsRpomRBhG+N8FJUzw8wQmTjAaTMeGhLIRpAODJHI44CQAyHfHTs7hJSB6yO8KWQp5AiLAIYdf09CU8hI8jbIzEID7yRH5Gwl/yJP0tZ4IsJ4eTJOOpvUwa3lOQIUrjLPs/j+N/W3qaZLqGITLIyWLf0Il6yJndS13iL2NhwvygaRbwpnqa4GSJb8Q0czNYsdPM43j6y9amzQ+Y5kSBN1uWJ5MdPs38DK+waRYvCZXVShSzmNPMEU/WJSIslaRGyPzJfLYsf25yeNQ0Zwki509zRmqY/0wMS+YXS0Jl/fOFPh4zdb1le0/P+Mt+BWzZ2szkcF/Z3jkz/fOFzJmcGdGy3nh8T6+ZmAhZvCjTQ1ZLlBYsi+en+cj8GVlhsrWZyAs5szZYdoYpHL/gaQYCEAg4gEuXnyYAMvk5mRMbYS0RLRMLkpIz6UzkhvHpbCHXYg7d2tLaGoCJ+zr1OrwLmbyHkEr7jG/drwC4XBwfHz874/O7CMAJB+SxNM34jBnIVSQBcL2JKxFnTfkm7xIGeXryyH+BGtACesAYmANrYA+cgTvwAn4gCISDGLAI6TUZpAMxyAYrwFpQAIrAFrADlIF94CCoBMfASdAAzoHL4Bq4BTpBD3gIpGAQvAIj4AMYgyAIB1EgKqQGaUMGkBlkDTEgV8gLCoBCoRgoHkqChJAEWgGtg4qgYqgMOgBVQSegJugydAPqgu5D/dAQ9Bb6AqNgMkyDNWFDeC7MgJmwPxwOL4ST4KVwLpwPb4JL4Qr4KFwPX4ZvwT2wFH4Fj6IAioRSQemgzFEMFAsVhIpFJaLEqFWoQlQJqgJVi2pGtaHuoKSoYdRnNBZNRdPR5mhntC86As1FL0WvQm9El6Er0fXoVvQddD96BP0dQ8FoYMwwThg2JhqThMnGFGBKMIcxZzBXMT2YQcwHLBargjXCOmB9sTHYFOxy7EbsHmwd9hK2CzuAHcXhcGo4M5wLLgjHwWXiCnC7cEdxF3HduEHcJzwJr423xnvjY/FCfB6+BF+Nv4Dvxj/HjxEUCAYEJ0IQgUdYRthMOERoJtwmDBLGiIpEI6ILMZyYQlxLLCXWEq8SHxHfkUgkXZIjKYQkIK0hlZKOk66T+kmfyUpkUzKLHEeWkDeRj5Avke+T31EoFEOKOyWWkknZRKmiXKE8oXySo8pZyLHleHKr5crl6uW65V7LE+QN5Jnyi+Rz5UvkT8nflh9WICgYKrAUOAqrFMoVmhT6FEYVqYpWikGK6YobFasVbyi+UMIpGSp5KfGU8pUOKl1RGqCiqHpUFpVLXUc9RL1KHaRhaUY0Ni2FVkQ7RuugjSgrKdsqRyrnKJcrn1eWqqBUDFXYKmkqm1VOqvSqfJmlOYs5iz9rw6zaWd2zPqrOVnVX5asWqtap9qh+UaOreamlqm1Va1B7rI5WN1UPUc9W36t+VX14Nm2282zu7MLZJ2c/0IA1TDVCNZZrHNRo1xjV1NL00RRp7tK8ojmspaLlrpWitV3rgtaQNlXbVVugvV37ovZLujKdSU+jl9Jb6SM6Gjq+OhKdAzodOmO6RroRunm6dbqP9Yh6DL1Eve16LXoj+tr6gfor9Gv0HxgQDBgGyQY7DdoMPhoaGUYZrjdsMHxhpGrENso1qjF6ZEwxdjNealxhfNcEa8IwSTXZY9JpCpvamSablpveNoPN7M0EZnvMuuZg5jjOEc6pmNNnTjZnmmeZ15j3W6hYBFjkWTRYvJ6rPzd27ta5bXO/W9pZplkesnxopWTlZ5Vn1Wz11trUmmtdbn3XhmLjbbPaptHmja2ZLd92r+09O6pdoN16uxa7b/YO9mL7WvshB32HeIfdDn0MGiOYsZFx3RHj6OG42vGc42cne6dMp5NOfzibO6c6Vzu/mGc0jz/v0LwBF10XjssBF6kr3TXedb+r1E3HjeNW4fbUXc+d537Y/TnThJnCPMp87WHpIfY44/GR5cRaybrkifL08Sz07PBS8orwKvN64q3rneRd4z3iY+ez3OeSL8bX33erbx9bk81lV7FH/Bz8Vvq1+pP9w/zL/J8GmAaIA5oD4UC/wG2Bj+YbzBfObwgCQeygbUGPg42ClwafDcGGBIeUhzwLtQpdEdoWRg1bHFYd9iHcI3xz+MMI4whJREukfGRcZFXkxyjPqOIoafTc6JXRt2LUYwQxjbG42MjYw7GjC7wW7FgwGGcXVxDXu9BoYc7CG4vUF6UtOr9YfjFn8al4THxUfHX8V04Qp4IzmsBO2J0wwmVxd3Jf8dx523lDfBd+Mf95okticeKLJJekbUlDyW7JJcnDApagTPAmxTdlX8rH1KDUI6njaVFpden49Pj0JqGSMFXYukRrSc6SLpGZqEAkXeq0dMfSEbG/+HAGlLEwozGThgijdomx5AdJf5ZrVnnWp+zI7FM5ijnCnPZlpss2LHue653783L0cu7ylhU6K9au6F/JXHlgFbQqYVXLar3V+asH1/isqVxLXJu69pc8y7zivPfrotY152vmr8kf+MHnh5oCuQJxQd965/X7fkT/KPixY4PNhl0bvhfyCm8WWRaVFH3dyN148yern0p/Gt+UuKljs/3mvVuwW4Rbere6ba0sVizOLR7YFritfjt9e+H29zsW77hRYluybydxp2SntDSgtHGX/q4tu76WJZf1lHuU1+3W2L1h98c9vD3de9331u7T3Fe078t+wf57B3wO1FcYVpQcxB7MOvjsUOShtp8ZP1cdVj9cdPjbEeERaWVoZWuVQ1VVtUb15hq4RlIzdDTuaOcxz2ONtea1B+pU6oqOg+OS4y9PxJ/oPel/suUU41TtaYPTu89QzxTWQ/XL6kcakhukjTGNXU1+TS3Nzs1nzlqcPXJO51z5eeXzmy8QL+RfGL+Ye3H0kujS8OWkywMti1seXom+crc1pLXjqv/V69e8r11pY7ZdvO5y/dwNpxtNNxk3G27Z36pvt2s/84vdL2c67Dvqbzvcbux07Gzumtd1odut+/IdzzvX7rLv3uqZ39PVG9F7ry+uT3qPd+/F/bT7bx5kPRh7uOYR5lHhY4XHJU80nlT8avJrndReer7fs7/9adjThwPcgVe/Zfz2dTD/GeVZyXPt51UvrF+cG/Ie6ny54OXgK9GrseGC3xV/3/3a+PXpP9z/aB+JHhl8I34z/nbjO7V3R97bvm8ZDR598iH9w9jHwk9qnyo/Mz63fYn68nws+yvua+k3k2/N3/2/PxpPHx8XccScSSmAQgacmAjA2yMAUGIAoHYi+mHBlJ6eNGjqG2CSwH/iKc09afYA1CJaOgTR7qw+AI4fQuQskl8+DoBgCgDhjgC2sZGNae07qdMnDIt8sewP+JaQngD+jU1p+L/0/c8ZTGS1Bf+c/wT+cgb9edcEzwAAAJZlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAACQAAAAAQAAAJAAAAABAAOShgAHAAAAEgAAAISgAgAEAAAAAQAAACCgAwAEAAAAAQAAACAAAAAAQVNDSUkAAABTY3JlZW5zaG909kiE/AAAAAlwSFlzAAAWJQAAFiUBSVIk8AAAAtdpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDYuMC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIj4KICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjM4MjwvZXhpZjpQaXhlbFhEaW1lbnNpb24+CiAgICAgICAgIDxleGlmOlVzZXJDb21tZW50PlNjcmVlbnNob3Q8L2V4aWY6VXNlckNvbW1lbnQ+CiAgICAgICAgIDxleGlmOlBpeGVsWURpbWVuc2lvbj4zODI8L2V4aWY6UGl4ZWxZRGltZW5zaW9uPgogICAgICAgICA8dGlmZjpSZXNvbHV0aW9uVW5pdD4yPC90aWZmOlJlc29sdXRpb25Vbml0PgogICAgICAgICA8dGlmZjpZUmVzb2x1dGlvbj4xNDQ8L3RpZmY6WVJlc29sdXRpb24+CiAgICAgICAgIDx0aWZmOlhSZXNvbHV0aW9uPjE0NDwvdGlmZjpYUmVzb2x1dGlvbj4KICAgICAgICAgPHRpZmY6T3JpZW50YXRpb24+MTwvdGlmZjpPcmllbnRhdGlvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+ClzTNacAAAYqSURBVFgJnVfdT1RXEP8BCyywW1g+FgQqiFiM1lrBh4LVFiVWm5A+NBVMMPBg+ANMDEmxfbDGB6w+SDRNeDNRbExTTTQkNhSjxqRVQVZTkPqBIIKFusAK8rVs72+2s9wVhNVJ7j3nzvfMmTPn3LD6+nrfo0ePEBsbi9nZWbwrhIWFiejk5CRqamqQkpICn88Hxb9Jr6W1tRX79+9HcnIypqenlxR4kyLiLRYLDhw4gJcvX4bugNPpRFZWlmRgMeWh0lasWBEqq/CFM2qmjeD1eiVt8mG8uCRM40KPebk412/VpTqWGsPJoOsUEREh82fPnkkaw8OFLDjymB/Snj9/juHhYXCuOnRcyrDS/Rb0yxjPnj2LjIwMlJaWor+/XxQzAwoaaXNzM9LS0uBwOHD//v2AA8oX6igOqIHR0VHs3r0bGzduxJUrV3D16lXRo3R+MFo6ceTIEURHRwv9woULMr7LSxzQtNntdhw8eBC3bt0SXevWrZunk87QibKyskDtFBUVzeMLFWExM9IRbsmtW7di2bJlyMnJkQKkQRrWh7VSUVGB1atXw2azgY6ygIknjy6TjmYb5jntBTlAAavVik2bNgkflZFJR80UiZGRkSgsLAzoo3FCVFRUYEuzLywFQRxqjAYJGjnxbC5PnjyRSBVPhw2S8Pn5I9DT0wOXqx0ejwcTExMBmig0vWiDzS/IAdJpzBypRt/R0YFvdn2N2m+/M3bHP7AYEXu9fgfIzyVwJCagt7fHKN5r6Or6e8HOSn0xMTFob2+XZZ7nAKPSCE0OY2pqCnV1PyLn/Y9w5/olOJLjEBsXbeCnjSUCPKPjyF+/HkVFHlRVVSI9Pd0sPm/+9OlTnDp1KjgD9I7GCZoFLSTiPaMeXDx/DT0PBuFIsaL2h9PYEJmH7E/fw68t/ejvdSNx+bAR+ZToYFYoRx2aSRJYL69evRJcUAbIzFSfOHEC+fn5UuksKgU6leKMx5h7GlXVpSjc/CHSM51ITXPgj8waZGQlYjrCYzg/FwRltECpxxwQv4McoFeVlZW4efMmacjMzMT27dtl7n+FGXt/CrkfJ+Oe6wFKvvgE1pgoqYVtu5xwv3DD7qRxfxEzaoLL5cKNGzdQUlKC3NxcwekryAF6GxcXpzQ5XgMfMjF6gTGODI/BOzOD8780o6Kq1OADbPYYjLg9sJsEGDl3xXqjNhQGBwel+gOZIEHXmz2goaEBtbW1aGxsxJYtW2SdVJgRWa2RcDUN4reLrSjavEEq/a6rE309Q7C/Z1xqfLzU+C8nlBsZGRFxjZzb2QyyWOoNi4aMhw4dQnl5uWSAOAKN83G/8KATQwi3+HCn7S4afmrEz6cvITHJhgd/DcBnFJwC+deuXStB0ca5c+eQnZ0tZA3a2M4Rsi+JNReLcBkv7WbsfHa7DQVfbYD7Xw8Sk+24/rsLlmgf4mwxiHfYUfb9l2i/96f0BMrTKHXu3bsXe/bsCRxepAUcYHc7fPiwXKEWupIxCp56nZ2d4Ppt2zYK53Lj6hbuRkZ8pEQ865uC1RaN7t4OnDxZb5yo5bQhRihPoA7O+ehWJ95SV1cHHsPqEZFmYBS8sMbHx+Phw4f4/LNiTExqi6XyufUm7+XLzUhNTRUV1Kl6aVjnZv0W3gdDARYTlaz6YFUo7MKjBjXyhQQtixEpwKhYBzxY9L7n9c4YlLkG87oOc4pJM2eC+tQx6g/nBwUWe4TR4JkT9BvnfbCrq0ucpLzqIj9BjY+Njcm1jQGYnSOPv2dyFgKoA6zsgYEBubjk5eXh+PHjIq10fqhxHsvV1dVyeWF/YSaVzvGtHBDJ/1+3b99GW1sbiouLsW/fPgwNDQmFhgk6MkNnzpzBzp07cfToUemMZvo7O6DttaWlRRpXUlKSGNYs6Lhy5Urs2LEDTU1NkgmeLwSlB50FQlnkxQIizBjnABVxGfgPsWbNGlGodPLQALtoQkKCZID/n1wubmmCZuitHOBZQdDuyP2ue5741wtMOyv/HQoKCsgSAOoif8gO0OPHjx/LnxCrmsLEMWo1FND+2kT51EFeybq7uzE+Ph66A/zd7uvrw7Fjx2QJ1AZTrelU3EKjmY8ZZNGygP8D78Xu31Bpyl8AAAAASUVORK5CYII=)

**Comment by ieahleen** [comment]
The Habitica gryphon is trademarked or something, and it's totally not going to be visible in a 16x16 image

**Comment by ShivSitaram** [comment]
Oh my bad then... is there something else we could put in the center?

**Comment by ieahleen** [comment]
At most I think a purple dot lol, or nothing at all.

**Comment by ShivSitaram** [comment]
LOL. I think nothing in the center *could* look nice... I'd be hesitant about putting a purple dot for the reason that you are not allowed to have purple be the main color in any of your third-party applications... the favicon represents your randomizer... I'd say it's probably best not to include purple. [Here's the part that says not to use purple](https://habitica.fandom.com/wiki/Guidance_for_Comrades#:~:text=However%20please%20limit%20your%20use%20of%20the%20several%20colors%20labelled%20as%20purple%20or%20other%20purple%20shades%20that%20are%20similar%20to%20them.)

**Comment by ieahleen** [comment]
@ShivSitaram make sure the image looks good reduced to 16x16px, and maybe give it a transparent backgroound?

**Comment by ShivSitaram** [comment]
@ieahleen Done. How do you like it?

<img width="8" alt="Screen_Shot_2022-10-17_at_9 31 17_AM-removebg-preview" src="https://user-images.githubusercontent.com/104377732/196260291-d51b01a2-49aa-447d-bb62-22fc3ea3cf43.png">

**Comment by ieahleen** [comment]
I think maybe it can go. You can open a PR if you want

**Comment by ShivSitaram** [comment]
Done 👍
